name: cd
on:
    workflow_dispatch:
    workflow_run:
        workflows: [ci]
        types: [completed]
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: "package.json"
            - run: npm install
            - run: npm run build
            - uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  command: deploy --var VERSION:${{ github.sha }}
